-- MySQL Script generated by MySQL Workbench
-- Tue Feb 12 20:56:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_salud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_salud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_salud` DEFAULT CHARACTER SET utf8 ;
USE `bd_salud` ;

-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_Lugar` (
  `cod_lugar` INT NOT NULL AUTO_INCREMENT,
  `lugar_hijo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_lugar`),
  CONSTRAINT `fk_Tbl_Lugar_Tbl_Lugar1`
    FOREIGN KEY (`lugar_hijo`)
    REFERENCES `bd_salud`.`Tbl_Lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_genero` (
  `cod_genero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_persona` (
  `ID_persona` INT NOT NULL AUTO_INCREMENT,
  `cod_lugar` INT NOT NULL,
  `cod_genero` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_persona`),
  CONSTRAINT `fk_Tbl_persona_Tbl_Lugar1`
    FOREIGN KEY (`cod_lugar`)
    REFERENCES `bd_salud`.`Tbl_Lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_persona_Tbl_genero1`
    FOREIGN KEY (`cod_genero`)
    REFERENCES `bd_salud`.`Tbl_genero` (`cod_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_Tipos_colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_Tipos_colaborador` (
  `tipo_colaborador` INT NOT NULL AUTO_INCREMENT,
  `colaborador` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tipo_colaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`tbl_centro_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`tbl_centro_medico` (
  `cod_centro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad_empledos` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_centro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_Colaborador` (
  `cod_colaborador` INT NOT NULL AUTO_INCREMENT,
  `tipo_colaborador` INT NOT NULL,
  `cod_centro_medico` INT NOT NULL,
  `numero_colaborador` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NULL,
  `correo` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_colaborador`),
  CONSTRAINT `fk_Tbl_Colaborador_Tbl_persona`
    FOREIGN KEY (`cod_colaborador`)
    REFERENCES `bd_salud`.`Tbl_persona` (`ID_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Colaborador_Tbl_Tipos_colaborador1`
    FOREIGN KEY (`tipo_colaborador`)
    REFERENCES `bd_salud`.`Tbl_Tipos_colaborador` (`tipo_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Colaborador_tbl_centro_medico1`
    FOREIGN KEY (`cod_centro_medico`)
    REFERENCES `bd_salud`.`tbl_centro_medico` (`cod_centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`tbl_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`tbl_horarios` (
  `cod_hora` INT NOT NULL,
  `horario` DATETIME NOT NULL,
  `nombre_turno` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`tbl_buses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`tbl_buses` (
  `cod_bus` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `hospital_asignado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`cod_bus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`tbl_rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`tbl_rutas` (
  `cod_ruta` INT NOT NULL AUTO_INCREMENT,
  `cod_hora` INT NOT NULL,
  `cod_bus` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_ruta`),
  CONSTRAINT `fk_tbl_rutas_tbl_horarios1`
    FOREIGN KEY (`cod_hora`)
    REFERENCES `bd_salud`.`tbl_horarios` (`cod_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_rutas_tbl_buses1`
    FOREIGN KEY (`cod_bus`)
    REFERENCES `bd_salud`.`tbl_buses` (`cod_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`tbl_centro_medico_has_tbl_rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`tbl_centro_medico_has_tbl_rutas` (
  `cod_Centro_ruta` INT NOT NULL,
  `tbl_centro_medico_cod_centro` INT NOT NULL,
  `tbl_rutas_cod_ruta` INT NOT NULL,
  PRIMARY KEY (`cod_Centro_ruta`, `tbl_centro_medico_cod_centro`, `tbl_rutas_cod_ruta`),
  CONSTRAINT `fk_centro_medico_X_ruta`
    FOREIGN KEY (`tbl_centro_medico_cod_centro`)
    REFERENCES `bd_salud`.`tbl_centro_medico` (`cod_centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ruta_X_centro_medico`
    FOREIGN KEY (`tbl_rutas_cod_ruta`)
    REFERENCES `bd_salud`.`tbl_rutas` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_salud`.`Tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_salud`.`Tbl_usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
